times = ('CORINTHIANS', 'PALMEIRAS','SANTOS', 'GRÊMIO', 'CRUZEIRO', 'FLAMENGO', 'VASCO DA GAMA', 'CHAPECOENSE', 'ATLÉTICO-MG', 'BOTAFOGO', 'ATLÉTICO-PR', 'BAHIA', 'SÃO PAULO', 'FLUMINENSE', 'SPORT RECIFE', 'EC VITÓRIA', 'CORITIBA', 'AVAÍ', 'PONTE PRETA', 'ATLÉTICO-GO')
print('=-=' * 31)
print(f'Os 5 PRIMEIROS colocados foram: {times[0:5]}')
print('=-=' * 31)
print(f'Os 4 ÚLTIMOS colocados foram: {times[-4:]}')
print('=-=' * 31)
print(f'Em ordem alfabética: {sorted(times)}')
print('=-=' * 31)
print(f'O time CHAPECOENSE está na posição: {times.index("CHAPECOENSE") + 1}ª')
